### ISSUE TITLE
Running your code on Windows machine!

### ISSUE THREAD

**Issue by a24ibrah** [jorendorff/tinysearch#5]
Hi Jason
I enjoyed trying your search engine on my Mac machine. The steps you mentioned was okay. However, when I tried on another machine with Windows installation I faced a problem with running your search engine. And, I get the following error: " 
Traceback (most recent call last):
  File "tiny.py", line 139, in <module>
    make_index(sys.argv[1])
  File "tiny.py", line 29, in make_index
    text = path.read_text()
  File "C:\Users\aibrah64\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1179, in read_text
    return f.read()
  File "C:\Users\aibrah64\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 15704: character maps to <undefined>

Can you help me with this? I don't why I got that message on Windows and not in Mac.
Regards,
Ahmed

**Comment by jorendorff** [comment]
Oh, `path.read_text()` should be `path.read_text(encoding='utf-8')` probably. I can fix it next time I'm at a keyboard.

**Comment by a24ibrah** [comment]
Hi Jason
I tried the modified file and I got the following message:
Traceback (most recent call last):
  File "tiny.py", line 139, in <module>
    make_index(sys.argv[1])
  File "tiny.py", line 49, in make_index
    out.writerow(doc)
  File "C:\Users\aibrah64\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position 4: character maps to <undefined>

**Comment by a24ibrah** [comment]
Hi Jason, I fixed the code. Please find attached./Volumes/Maple/tiny/tiny.py
